services:
  db:
    image: postgres:15-alpine
    container_name: bizler-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-bizler}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: bizler-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-bizler}?schema=public
      SECRET_KEY: ${SECRET_KEY:-my_super_secret_key_123}
      USER_PASSWORD: ${USER_PASSWORD}
      BOT_TOKEN: ${BOT_TOKEN}
      PORT: 8080
    depends_on:
      - db

volumes:
  pgdata:
